version: 0.2

env:
  parameter-store:
    DATABASE: "pet-dashboard-database-connection-uri"
    DATABASE_TEST: "pet-dashboard-test-database-connection-uri"

phases:
  pre_build:
    commands:
      - cd server && yarn install --silent
      - yarn global add serverless
  build:
    commands:
      - ./startOffline.sh
      - yarn test
      - ./stopOffline.sh