service: pet-dayboard-serverless-api # Replace this with your AWS severless service name

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can define service wide environment variables here
  environment:
    DATABASE: ${env:DATABASE}
    DATABASE_TEST: ${env:DATABASE_TEST}

functions:
  healthcheck:
    handler: handler.healthcheck
    events:
      - http:
          path: /
          method: get
          cors: true
  
  create:
    handler: handler.create
    events:
      - http:
          path: pet
          method: post
          cors: true
  
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: pet/{id}
          method: get
          cors: true
          request: 
            parameters: 
              paths: 
                id: true
  
  getAll:
    handler: handler.getAll 
    events:
      - http:
          path: pet
          method: get
          cors: true
  
  update:
    handler: handler.update
    events:
      - http:
          path: pet/{id}
          method: put
          cors: true
          request: 
            parameters: 
              paths: 
                id: true
  
  delete:
    handler: handler.delete
    events:
      - http:
          path: pet/{id}
          method: delete
          cors: true
          request: 
            parameters: 
              paths: 
                id: true
    
  deleteAll:
    handler: handler.deleteAll
    events:
      - http:
          path: pet/purge
          method: delete
          cors: true

plugins:
  - serverless-offline